name: CI

on:
  push:
  pull_request:

jobs:
  buildAndTest:
    runs-on: ubuntu-24.04
    container:
      image: "ubuntu:24.04"
    steps:
      - uses: actions/checkout@v6

      - name: Install fast-apt-mirror's dependencies
        run: |
          apt update --yes

          apt install --yes --no-install-recommends ca-certificates curl

      - name: Select best APT mirror
        env:
          # last tag "refs/tags/1.4.2" doesn't contain latest fixes yet wrt https://github.com/vegardit/fast-apt-mirror.sh/issues/19
          FAST_APT_MIRROR_VERSION: "refs/heads/v1"
        run: |
          curl "https://raw.githubusercontent.com/vegardit/fast-apt-mirror.sh/$FAST_APT_MIRROR_VERSION/fast-apt-mirror.sh" -o ./fast-apt-mirror.sh
          chmod 755 ./fast-apt-mirror.sh
          ./fast-apt-mirror.sh find --apply --verbose
          rm ./fast-apt-mirror.sh

      - name: Install APT dependencies
        run: |
          # NOTE: do not change the below with an `actions/setup-node` step!
          # we don't like our CI steps to be a blackbox that is not easier to mimic by devs
          # (and this way we're testing with official Ubuntu packages, not whatever the GitHub/NodeJS guys fancy)
          apt install --yes --no-install-recommends npm

      - name: Print versions
        run: node --version && npm --version

      - name: Install NPM dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run linter (type check)
        run: npm run lint

      - name: Run tests
        run: npm test

