name: CI

on:
  push:
  pull_request:

jobs:
  calc-docker-img-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.md5sum.outputs.tag }}
    steps:
      - uses: actions/checkout@v6
      - name: Compute MD5 sum of Dockerfile
        id: md5sum
        run: |
          echo "tag=$(md5sum Dockerfile | awk '{print $1}')" >> $GITHUB_OUTPUT

  docker-img-build-push:
    needs: calc-docker-img-tag
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if image exists
        id: check
        run: |
          TAG=${{ needs.calc-docker-img-tag.outputs.tag }}
          IMAGE=ghcr.io/${{ github.repository_owner }}/fp-sdk-ci:$TAG
          if docker manifest inspect $IMAGE > /dev/null 2>&1; then
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Build and push image
        if: steps.check.outputs.image_exists == 'false'
        run: |
          TAG=${{ needs.calc-docker-img-tag.outputs.tag }}
          IMAGE=ghcr.io/${{ github.repository_owner }}/fp-sdk-ci
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

  build-and-test:
    needs: [calc-docker-img-tag, docker-img-build-push]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/fp-sdk-ci:${{ needs.calc-docker-img-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v6

      - name: Print versions
        run: node --version && npm --version
      - name: Install NPM dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run linter (type check)
        run: npm run lint
      - name: Run tests
        run: npm test

