name: CI

on:
  push:
  pull_request:

jobs:
  buildAndTest:
    runs-on: ubuntu-24.04
    container:
      image: "ubuntu:24.04"
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt update --yes

          # NOTE: do not change the below with an `actions/setup-node` step! or it
          # would make this CI job entirely pointless
          apt install --yes --no-install-recommends npm

      - name: Print versions
        run: node --version && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run linter (type check)
        run: npm run lint

      - name: Run tests
        run: npm test

